---
- functions:
  - {name: unsafePerformIO, within: []}
  - {name: undefined, within: [Package.C.Db.Register]}
  - {name: fromJust, within: []}
  - {name: foldl, within: []}
  - {name: traceShowId, within: []}
  - {name: traceShow, within: []}
  - {name: diagnosticDirectory, within: []}

- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Use section"}

- error: {lhs: "f *> pure ()", rhs: "void f", name: "Use void"}
- error: {lhs: "over _1 f x", rhs: "first f x", name: "Use arrows"}
- error: {lhs: "over _2 f x", rhs: "second f x", name: "Use arrows"}
- error: {lhs: "bool x x p", rhs: "x", name: "Redundant bool"}
- error: {lhs: "maybe mempty", rhs: "foldMap", name: "Use foldMap"}
- error: {lhs: "if p then x else pure ()", rhs: "when p x"}
- error: {lhs: "fmap (pure ())", rhs: "void", name: "Use void"}

- fixity: infixr 3 ***
- fixity: infixr 3 &&&
- fixity: infixr 1 <=<
- fixity: infixr 1 <=*<
