---

build: off

before_test:
  - choco install ghc
  - choco install cabal
  - choco install pkgconfiglite
  - choco install GnuWin

test_script:
  - refreshenv
  - cabal new-update
  - cabal new-build
  - ps: $directory = Get-ChildItem . -name -recurse cpkg.exe
  - ps: Copy-Item $directory cpkg-x86_64-pc-windows.exe
  - ps: Push-AppveyorArtifact cpkg-x86_64-pc-windows.exe

deploy:
  artifacts: cpkg-x86_64-pc-windows.exe
  provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: 0qzMr6xmEwRoj/9TJOgDuW/LXWfGVM/4A7kvAXGe0BAwWCF13AWE2SARrYkyc3ji

branches:
  only:
    - master
    - /\d+\.\d+\.\d+\.\d+.*$/
