jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-haskell@v1"
        with:
          cabal-version: "3.0"
          ghc-version: "8.6.5"
      - name: "Install dhall"
        run: |
          cabal update
          cd "$(mktemp -d /tmp/dhall-XXX)"
          cabal install dhall
      - name: "Check Dhall"
        run: |
          export PATH=$HOME/.cabal/bin:$PATH
          dhall --file pkgs/pkg-set.dhall
          dhall --file dhall/cpkg-prelude.dhall
          dhall --file dhall/cpkg-types.dhall
          dhall --file dhall-ci.dhall
          dhall --file haskell-ci.dhall
name: "Dhall CI"
on:
  - push
  - pull_request
